docker run -d \
    -p 5000:5000 \
    -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
    -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
    -e AWS_DEFAULT_REGION="us-east-2" \
    -e GOOGLE_APPLICATION_CREDENTIALS="/app/data/google_credential.json" \
    -v "$(pwd)":/app \
    -v ${GOOGLE_APPLICATION_CREDENTIALS}:/app/data/google_credential.json \
    --env-file env_var \
    --network synapse-bridge \
    --name synapse-core synapse-core
